# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  socks5_server_config = debug
  echo_server_config = debug
endif
ifeq ($(config),release)
  socks5_server_config = release
  echo_server_config = release
endif

PROJECTS := socks5_server echo_server

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

socks5_server:
ifneq (,$(socks5_server_config))
	@echo "==== Building socks5_server ($(socks5_server_config)) ===="
	@${MAKE} --no-print-directory -C . -f socks5_server.make config=$(socks5_server_config)
endif

echo_server:
ifneq (,$(echo_server_config))
	@echo "==== Building echo_server ($(echo_server_config)) ===="
	@${MAKE} --no-print-directory -C . -f echo_server.make config=$(echo_server_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f socks5_server.make clean
	@${MAKE} --no-print-directory -C . -f echo_server.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   socks5_server"
	@echo "   echo_server"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"